In [1]:
import mlr

In [2]:
mlr.demo(10)

Data loaded successfully.
Data splitted for validation.
[[1.00e+00 3.00e+00 1.00e+00 1.57e+03 1.00e+00]
 [1.00e+00 3.00e+00 2.50e+00 1.78e+03 1.00e+00]
 [1.00e+00 3.00e+00 1.50e+00 1.09e+03 1.00e+00]
 ...
 [1.00e+00 3.00e+00 2.25e+00 2.36e+03 1.00e+00]
 [1.00e+00 4.00e+00 2.00e+00 2.37e+03 2.00e+00]
 [1.00e+00 4.00e+00 2.25e+00 2.38e+03 1.00e+00]]
[495000. 635000. 382500. ... 431000. 411000. 699900.]
The coeffients are [65340.2496976126]
The first five predictions are [416231.1121185218]
The actual values are 297000.0
The average absolute relative deviation is: 0.3535546136605877


In [4]:
import pandas as pd
data = pd.read_csv('kc_house_data.csv')

In [7]:
data.sample(3)

id             date     price  bedrooms  bathrooms  \
11393  5438000160  20140609T000000  213400.0         3        1.5   
9392   2212200100  20141022T000000  229950.0         4        2.5   
17753  2599700040  20141230T000000  160000.0         4        1.0   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
11393         1150      8686     1.0           0     0  ...      7   
9392          2150      7670     1.0           0     0  ...      7   
17753         1540      7350     1.0           0     0  ...      6   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
11393        1150              0      1963             0    98055  47.4417   
9392         1240            910      1976             0    98031  47.3942   
17753         770            770      1969             0    98023  47.3318   

          long  sqft_living15  sqft_lot15  
11393 -122.194           1760        8798  
9392  -122.189           1610        7350  
17753 -122.340            910        8000  

[3 rows x 21 columns]

In [8]:
y = data['price']

In [12]:
x = data[['bedrooms', 'bathrooms', 'sqft_living', 'floors']]

In [13]:
x

bedrooms  bathrooms  sqft_living  floors
0             3       1.00         1180     1.0
1             3       2.25         2570     2.0
2             2       1.00          770     1.0
3             4       3.00         1960     1.0
4             3       2.00         1680     1.0
...         ...        ...          ...     ...
21608         3       2.50         1530     3.0
21609         4       2.50         2310     2.0
21610         2       0.75         1020     2.0
21611         3       2.50         1600     2.0
21612         2       0.75         1020     2.0

[21613 rows x 4 columns]

In [15]:
import numpy as np
x_train = np.asmatrix(x)

In [17]:
print(x_train)

[[3.00e+00 1.00e+00 1.18e+03 1.00e+00]
 [3.00e+00 2.25e+00 2.57e+03 2.00e+00]
 [2.00e+00 1.00e+00 7.70e+02 1.00e+00]
 ...
 [2.00e+00 7.50e-01 1.02e+03 2.00e+00]
 [3.00e+00 2.50e+00 1.60e+03 2.00e+00]
 [2.00e+00 7.50e-01 1.02e+03 2.00e+00]]


In [18]:
x_train2 = np.append(np.asmatrix(np.tile(1, x_train.shape[0])).transpose(), x_train, axis=1)

In [19]:
x_train2

matrix([[1.00e+00, 3.00e+00, 1.00e+00, 1.18e+03, 1.00e+00],
        [1.00e+00, 3.00e+00, 2.25e+00, 2.57e+03, 2.00e+00],
        [1.00e+00, 2.00e+00, 1.00e+00, 7.70e+02, 1.00e+00],
        ...,
        [1.00e+00, 2.00e+00, 7.50e-01, 1.02e+03, 2.00e+00],
        [1.00e+00, 3.00e+00, 2.50e+00, 1.60e+03, 2.00e+00],
        [1.00e+00, 2.00e+00, 7.50e-01, 1.02e+03, 2.00e+00]])

In [21]:
print(x_train2)

[[1.00e+00 3.00e+00 1.00e+00 1.18e+03 1.00e+00]
 [1.00e+00 3.00e+00 2.25e+00 2.57e+03 2.00e+00]
 [1.00e+00 2.00e+00 1.00e+00 7.70e+02 1.00e+00]
 ...
 [1.00e+00 2.00e+00 7.50e-01 1.02e+03 2.00e+00]
 [1.00e+00 3.00e+00 2.50e+00 1.60e+03 2.00e+00]
 [1.00e+00 2.00e+00 7.50e-01 1.02e+03 2.00e+00]]


In [22]:
y_train2 = np.ravel(y)

In [23]:
y_train2

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [25]:
from mlr import MLR

In [26]:
model = MLR()

In [27]:
model.fit(x_train2, y_train2)

In [29]:
pred = model.predict(x_train2)

In [35]:
print(pred)

[[274263.81063231]
 [714337.79902534]
 [205260.55056711]
 ...
 [280845.97474412]
 [416189.746655  ]
 [280845.97474412]]


In [38]:
model.coef()

matrix([[ 74669.67315549],
        [-57847.96409567],
        [  7853.52160193],
        [   309.39322966],
        [   200.49716233]])

In [43]:
print('they are {!s}'.format(model.coef()))

they are [[ 74669.67315549]
 [-57847.96409567]
 [  7853.52160193]
 [   309.39322966]
 [   200.49716233]]


In [46]:
print('pred is {!s}'.format(pred[:5]))

pred is [[274263.81063231]
 [714337.79902534]
 [205260.55056711]
 [473449.60887581]
 [436813.94706456]]


In [47]:
print('y is {!s}'.format(y[:5]))

y is 0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64
